---
title: "Learning Reflection"
subtitle: "Week 4"
format:
  html:
    embed-resources: true
editor: visual
---

# Learning reflections

Learning reflections are part of your weekly homework and have a weight of 20% of your final grade. Write a reflection in your own words on the different parts of the weeks material below. You can also use your learning reflections as a notebook as you work through exercises or readings. Write as much as you like, but a minimum of 100 words in total.

# Lecture

This lecture was very informative. I will certainly be using many of these skills in my practicum assignment, which I am using as my Capstone Project. I want to get more comfortable with the functions that remove ‘na’ because a lot of my data will have wholes in it.

# Homework Assignment

This was an especially helpful homework. I expect to be using mutate() select() and group_by() a lot, so it was nice to get some exposure to writing it myself while also having your solutions on the other file. I also think gt() will be very helpful for my data visualization and I would like to understand it better.

# Readings

[R for Data Science – Data Transformation:]{.underline} It was nice to have the different variable types explained at the beginning as well as revisiting the dplyr basics. The examples of filtering for ‘na’ as well as the helper functions within select() were also helpful and I will certainly be revisiting later in my data analysis.

[Excuse Me, Do You Have a Moment to Talk About Version Control?]{.underline} : I did not know Git was built to be a version control system. “Recall that a repository or repo is just a directory of files that Git manages holistically. A commit functions like a snapshot of all the files in the repo, at a specific moment.” This paper helped explain some of the functions and purpose of Github, but I am still a bit fuzzy on how posit.cloud comes into play. My understanding is posit.cloud is where we do the editing in R, and Github is like our storage base for our projects as we iterate and work on them. I am not supe confident in that understanding though.

# Submit learning reflections

## Stage, Commit & Push to GitHub

This final section introduces the workflow you need to follow at the end of each live coding exercise, homework assignment, learning reflection. It ensures that all the changes you have made to files in this repository (folder) are synced with the version that is stored on GitHub. The steps will be described at the end of each of the files.

1.  Open the Git pane in RStudio. It's in the top right corner in a separate tab.
2.  **Stage** your changes by checking appropriate box next to all files (if you select one file with your mouse, you can then highlight them all with Ctrl + A on your keyboard and check all boxes)
3.  Write a meaningful commit message (e.g. "Completed homework assignment 1b) in the **Commit message** box
4.  Click **Commit**. Note that every commit needs to have a commit message associated with it.
5.  Go to your course-material GitHub repo and refresh the page. You should see your commit message next to the updated files.

## Open an issue on GitHub

Once you have ensured that the Quarto document renders without errors and you have pushed all your changes to GitHub, it is to complete the assignment by opening an issue on your course-material GitHub repo.

1.  Navigate to your course-material GitHub repo.
2.  Click on **Issues**, and then **New issue** button.
3.  Write a meaningful title in the **Title** field
4.  Tag the course instructor with using the `@` sign in combination with `larnsce` as the username
5.  Add any questions or comments
